name: "pr_title_check"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: checkout
      - run: |
          cd pr_title_check
          yarn install
          echo "---------------------------------------"
          yarn run build
        name: build
      - run: |
          cd pr_title_check
          yarn run tests
        name: unit tests
      - run: |
          cd pr_title_check
          yarn run integration
        name: integration tests

  # Nothing really to test, becuase it's for PRs
  test_e2e: # make sure the action works on a clean machine without building
    #needs:
    #  - build_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./pr_title_check
        with:
          message: PR title does not match
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          matchJira: 1
